name:                hpcre2
version:             0.1.0.0
github:              "robwithhair/hpcre2"
license:             MIT
author:              "Rob Harrison"
maintainer:          "rob@flowmo.co"
copyright:           "2020 Rob Harrison"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A PCRE2 Library for Haskell
category:            Regular Expressions

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A binding to the popular PCRE2 C Regular expression library.  Please see the README on GitHub at <https://github.com/robwithhair/hpcre2#readme> for further information.

dependencies:
- base >= 4.7 && < 5
- vector
- text
- bytestring

library:
  source-dirs: src
  ghc-options:
    - -optc "-DPCRE2_CODE_UNIT_WIDTH=8"
  extra-libraries:
    - pcre2-8

executables:
  hpcre2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpcre2
    extra-libraries:
      - pcre2-8

tests:
  hpcre2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpcre2
